# action.yml
name: "Ziploy"
icon: "archive"
color: "green"
description: "Deploy WordPress Theme or Plugin directly from GitHub to any hosting"

inputs:
    ziploy-method:
        description: "Deployment mode (SSH, FTP, JWT)"
        required: false
        default: "SSH"

    ziploy-id:
        description: "Ziploy ID"
        required: true

    ziploy-host:
        description: "Ziploy Origin"
        required: true

    ziploy-ssh-host:
        description: "SSH Host"
        required: true

    ziploy-ssh-user:
        description: "SSH User"
        required: true

    ziploy-ssh-port:
        description: "SSH Port"
        required: false
        default: "22"

    ziploy-ssh-key:
        description: "SSH Private Key"
        required: true

runs:
    using: "docker"
    image: "Dockerfile"
    env:
        ZIPLOY_METHOD: ${{ inputs.ziploy-method }}
        ZIPLOY_ID: ${{ inputs.ziploy-id }}
        ZIPLOY_HOST: ${{ inputs.ziploy-host }}
        ZIPLOY_SSH_HOST: ${{ inputs.ziploy-ssh-host }}
        ZIPLOY_SSH_USER: ${{ inputs.ziploy-ssh-user }}
        ZIPLOY_SSH_PORT: ${{ inputs.ziploy-ssh-port }}
        ZIPLOY_SSH_KEY: ${{ inputs.ziploy-ssh-key }}
    args:
        - ${{ inputs.ziploy-method }}
        - ${{ inputs.ziploy-id }}
        - ${{ inputs.ziploy-host }}
        - ${{ inputs.ziploy-ssh-host }}
        - ${{ inputs.ziploy-ssh-user }}
        - ${{ inputs.ziploy-ssh-port }}
        - ${{ inputs.ziploy-ssh-key }}
