# action.yml
name: "Ziploy"
description: "Deploy WordPress Theme or Plugin directly from GitHub to any hosting"

branding:
    icon: "archive"
    color: "green"

inputs:
    ziploy-username:
        description: "WP Application User name"
        required: true

    ziploy-password:
        description: "WP Application User password"
        required: true

    ziploy-working-directory:
        description: "Path to working directory if it's different from git root directory, eg: wp-content/themes/my-theme"
        required: false

runs:
    using: "docker"
    image: "Dockerfile"
    env:
        ZIPLOY_WP_APP_USER: ${{ inputs.ziploy-username }}
        ZIPLOY_WP_APP_PASS: ${{ inputs.ziploy-password }}
        ZIPLOY_WORKING_DIRECTORY: ${{ inputs.ziploy-working-directory }}
